apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: orangered-send-emails
  labels:
    app: orangered-cron
spec:
  schedule: "0 12 * * *"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: orangered
              image: gcr.io/orangered/orangered
              args:
                - ./send_emails
              env:
                - name: MAILGUN_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: mailgun-creds
                      key: mailgun-api-key
                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      name: psql-creds
                      key: pgdatabase
                - name: PGHOST
                  valueFrom:
                    secretKeyRef:
                      name: psql-creds
                      key: pghost
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: psql-creds
                      key: pguser
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: psql-creds
                      key: pgpassword
                - name: REDDIT_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: reddit-creds
                      key: reddit-client-id
                - name: REDDIT_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: reddit-creds
                      key: reddit-client-secret
                - name: REDDIT_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: reddit-creds
                      key: reddit-username
                - name: REDDIT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: reddit-creds
                      key: reddit-password
                - name: SERVER_NAME
                  value: orangered.io
          restartPolicy: OnFailure
