apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: orangered-send-emails
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: orangered
              image: gcr.io/orangered/orangered
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
