apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orangered
  labels:
    app: orangered
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: orangered
    spec:
      containers:
        - name: orangered
          image: gcr.io/orangered/orangered
          ports:
            - name: http
              containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health_check
              port: 5000
          env:
            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mailgun-creds
                  key: mailgun-api-key
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: psql-creds
                  key: pgdatabase
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: psql-creds
                  key: pghost
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: psql-creds
                  key: pguser
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: psql-creds
                  key: pgpassword
            - name: REDDIT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: reddit-creds
                  key: reddit-client-id
            - name: REDDIT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: reddit-creds
                  key: reddit-client-secret
            - name: REDDIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: reddit-creds
                  key: reddit-username
            - name: REDDIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reddit-creds
                  key: reddit-password
            - name: SERVER_NAME
              value: "orangered.io"
