#!/usr/bin/env python3
from collections import OrderedDict

from bs4 import BeautifulSoup

import requests


def scrape_subreddits():
    resp = requests.get(
        'https://www.reddit.com/r/ListOfSubreddits/wiki/listofsubreddits',
        headers={'User-agent': 'orangered 0.1'},
    )
    soup = BeautifulSoup(resp.content, 'html.parser')
    subreddits_dict = OrderedDict()
    for link in soup.find('div', class_='md').find_all('a'):
        href = link.attrs['href']
        if href.startswith('/r/') and href != '/r/ListOfSubreddits':
            try:
                category = link.parent.find_previous_sibling().text
            except Exception as e:
                print(f"error at link: {link} {e}")
                continue
            if not category:
                continue
            if category in subreddits_dict:
                subreddits_dict[category].add(href.replace('/r/', ''))
            else:
                subreddits_dict[category] = {href.replace('/r/', '')}
    print("[")
    for category in subreddits_dict.keys():
        subreddits = sorted(subreddits_dict[category], key=lambda s: s.lower())
        print(f"    ('{category}', {subreddits}),")
    print("]")


if __name__ == '__main__':
    scrape_subreddits()
