#!/usr/bin/env python3
from utils import reddit_client


def search_subreddits(query):
    reddit = reddit_client()
    result = reddit.subreddits.search_by_name(query)
    pass


if __name__ == '__main__':
    search_subreddits("pelo")
