SUBREDDIT_INFO = [
    ('Gifs', ['behindthegifs', 'bettereveryloop', 'brokengifs', 'cinemagraphs', 'combinedgifs', 'educationalgifs', 'gif', 'gifextra', 'gifrecipes', 'gifs', 'gifsound', 'gifsthatkeepongiving', 'highqualitygifs', 'loadingicon', 'mechanical_gifs', 'michaelbaygifs', 'noisygifs', 'perfectloops', 'retiredgif', 'slygifs', 'splitdepthgifs', 'wastedgifs', 'wholesomegifs']),
    ('People', ['asianpeoplegifs', 'blackpeoplegifs', 'scriptedasiangifs', 'whitepeoplegifs']),
    ('Reaction', ['reactiongifs', 'shittyreactiongifs']),
    ('Science Gifs', ['chemicalreactiongifs', 'physicsgifs']),
    ('Nature Gifs', ['babyelephantgifs', 'weathergifs']),
    ('Images', ['dogpictures', 'expectationvsreality', 'fifthworldpics', 'foundpaper', 'images', 'itookapicture', 'miniworlds', 'misleadingthumbnails', 'nocontextpics', 'pareidolia', 'perfecttiming', 'photoshopbattles', 'pic', 'pics', 'thewaywewere']),
    ('Interesting', ['beamazed', 'damnthatsinteresting', 'interestingasfuck', 'mildlyinteresting', 'reallifeshinies']),
    ('Photoshop', ['colorization', 'colorizedhistory', 'hybridanimals', 'photoshopbattles', 'reallifedoodles']),
    ('Redditors/Selfies', ['amiugly', 'prettygirlsuglyfaces', 'rateme', 'roastme', 'uglyduckling']),
    ('Wallpapers', ['offensive_wallpapers', 'wallpaper', 'wallpapers']),
    ('Videos', ['artisanvideos', 'deepintoyoutube', 'killthecameraman', 'nottimanderic', 'praisethecameraman', 'videos', 'youtubehaiku']),
    ('Discussion - General', ['casualconversation', 'changemyview', 'crazyideas', 'doesanybodyelse', 'howtonotgiveafuck', 'quotes', 'showerthoughts', 'tipofmytongue']),
    ('Advice', ['advice', 'bestoflegaladvice', 'legaladvice', 'raisedbynarcissists', 'relationship_advice']),
    ('AMA', ['ama', 'casualiama', 'de_iama', 'explainlikeiama', 'iama']),
    ('Discussion - Games', ['askouija', 'scenesfromahat', 'whowouldwin', 'wouldyourather']),
    ('Question/Answer', ['amiugly', 'answers', 'nostupidquestions', 'samplesize', 'tooafraidtoask', 'whatisthisthing', 'whatsthisbug', 'whatsthisplant']),
    ('Ask______', ['askouija', 'askreddit', 'asksciencefiction', 'shittyaskscience', 'trueaskreddit']),
    ('Occupation', ['askculinary', 'askengineers', 'askhistorians', 'askphilosophy', 'askscience', 'asksocialscience']),
    ('Sex/Gender', ['askgaybros', 'askmen', 'askredditafterdark', 'asktransgender', 'askwomen']),
    ('Stories', ['confession', 'confessions', 'fatpeoplestories', 'self', 'tifu']),
    ('Customer Service', ['idontworkherelady', 'kitchenconfidential', 'starbucks', 'talesfromcallcenters', 'talesfromretail', 'talesfromtechsupport', 'talesfromthecustomer', 'talesfromthefrontdesk', 'talesfromthepharmacy', 'talesfromthepizzaguy', 'talesfromthesquadcar', 'talesfromyourserver', 'techsupportmacgyver']),
    ('Revenge', ['pettyrevenge', 'prorevenge']),
    ('Scary/Weird', ['glitch_in_the_matrix', 'letsnotmeet', 'nosleep', 'shortscarystories', 'thetruthishere', 'unresolvedmysteries', 'unsolvedmysteries']),
    ('Support', ['anxiety', 'depression', 'foreveralone', 'offmychest', 'socialanxiety', 'suicidewatch', 'trueoffmychest']),
    ('Educational - General', ['applyingtocollege', 'bulletjournal', 'changemyview', 'college', 'education', 'educationalgifs', 'everymanshouldknow', 'foodforthought', 'getstudying', 'howto', 'lawschool', 'learnuselesstalents', 'lectures', 'teachers', 'watchandlearn', 'youshouldknow']),
    ('Facts', ['todayilearned', 'wikipedia']),
    ('Questions', ['iwanttolearn', 'outoftheloop']),
    ('Explain Like...', ['explainlikeiama', 'explainlikeimcalvin', 'explainlikeimfive']),
    ('Anthropology', ['anthropology']),
    ('Art', ['animation', 'art', 'artfundamentals', 'artporn', 'breadstapledtotrees', 'drawing', 'graffiti', 'heavymind', 'illustration', 'learnart', 'pixelart', 'redditgetsdrawn', 'retrofuturism', 'sketchdaily', 'specart', 'streetart', 'wimmelbilder']),
    ('Painting', ['minipainting', 'painting']),
    ('Computer Science/Engineering', ['askengineers', 'cscareerquestions', 'engineering', 'engineeringstudents', 'gamedev', 'ubuntu']),
    ('Coding - Tech', ['artificial', 'coding', 'compsci', 'cpp', 'howtohack', 'java', 'javascript', 'learnprogramming', 'machinelearning']),
    ('Python', ['learnpython', 'python']),
    ('Economics', ['basicincome', 'business', 'economics', 'entrepreneur', 'marketing']),
    ('Business', ['business', 'smallbusiness']),
    ('Stocks', ['stockmarket', 'stocks', 'wallstreetbets']),
    ('Environment', ['environment', 'zerowaste']),
    ('History', ['100yearsago', 'askhistorians', 'badhistory', 'colorizedhistory', 'history']),
    ('Historical Images', ['castles', 'historymemes', 'historyporn', 'propagandaposters', 'thewaywewere']),
    ('Language', ['french', 'languagelearning', 'learnjapanese', 'linguistics']),
    ('Law', ['law']),
    ('Math', ['math', 'theydidthemath']),
    ('Medicine', ['medicalschool']),
    ('Psychology', ['jordanpeterson', 'psychology']),
    ('Science', ['askscience', 'cogsci', 'everythingscience', 'geology', 'medicine', 'science']),
    ('Astronomy', ['astronomy', 'astrophotography', 'nasa', 'space', 'spaceporn', 'spacex']),
    ('Biology', ['awwducational', 'biology']),
    ('Chemistry', ['chemicalreactiongifs', 'chemistry']),
    ('Physics', ['physics']),
    ('Entertainment - General', ['disney', 'entertainment', 'fantheories', 'obscuremedia']),
    ('Anime/Manga', ['anime', 'anime_irl', 'animegifs', 'animemes', 'animesuggest', 'animewallpaper', 'awwnime', 'manga', 'tsunderesharks']),
    ('Individual Anime/manga', ['berserk', 'bokunoheroacademia', 'dbz', 'ddlc', 'hunterxhunter', 'naruto', 'onepiece', 'onepunchman', 'pokemon', 'shingekinokyojin', 'tokyoghoul', 'yugioh']),
    ('Books/Writing', ['books', 'booksuggestions', 'boottoobig', 'freeebooks', 'hfy', 'lifeofnorman', 'literature', 'lovecraft', 'poetry', 'screenwriting', 'suggestmeabook', 'writing', 'writingprompts']),
    ('Comics', ['bertstrips', 'comicbooks', 'comics', 'defenders', 'marvel', 'marvelstudios', 'polandball', 'webcomics']),
    ('Individual books/stories/comics', ['arrow', 'batman', 'calvinandhobbes', 'dccomics', 'deadpool', 'harrypotter', 'kingkillerchronicle', 'spiderman', 'unexpectedhogwarts', 'xkcd']),
    ('Game of Thrones', ['asoiaf', 'freefolk', 'gameofthrones']),
    ('Lord of the Rings', ['lotr', 'lotrmemes', 'tolkeinfans']),
    ('Images/Gifs of Women (SFW)', ['bois', 'fitandnatural', 'gentlemanboners', 'gentlemanbonersgifs', 'girlsmirin', 'goddesses', 'hardbodies', 'prettygirls', 'shorthairedhotties', 'skinnywithabs', 'wrestlewiththeplot']),
    ('Celebrities', ['celebhub', 'celebs']),
    ('Individual Celebrities - Female', ['alexandradaddario', 'alisonbrie', 'emilyratajkowski', 'emmawatson', 'jenniferlawrence', 'jessicanigri', 'kateupton']),
    ('Individual Celebrities - Male', ['crewscrew', 'donaldglover', 'elonmusk', 'joerogan', 'keanubeingawesome', 'onetruegod']),
    ('Cosplay', ['cosplay', 'cosplaygirls']),
    ('Games', ['boardgames', 'chess', 'jrpg', 'lego', 'poker', 'rpg']),
    ('Dungeons and Dragons', ['criticalrole', 'dmacademy', 'dnd', 'dndbehindthescreen', 'dndgreentext', 'dndnext', 'dungeonsanddragons']),
    ('Magic', ['magictcg', 'modernmagic']),
    ('Video Games - General', ['androidgaming', 'emulation', 'gamecollecting', 'gamemusic', 'gamephysics', 'gamernews', 'gamersriseup', 'games', 'gaming', 'gaming4gamers', 'gamingcirclejerk', 'gamingdetails', 'hitboxporn', 'indiegaming', 'mmorpg', 'outside', 'patientgamers', 'randomactsofgaming', 'retrogaming', 'speedrun', 'truegaming', 'webgames']),
    ('Deals', ['freegamefindings', 'freegamesonsteam', 'gamedeals', 'nintendoswitchdeals', 'ps4deals', 'shouldibuythisgame', 'steamdeals']),
    ('Game Systems/Consoles/Companies', ['oculus', 'paradoxplaza', 'vive', 'xboxone']),
    ('PC', ['gamingpc', 'linux_gaming', 'pcgaming', 'pcmasterrace', 'steam']),
    ('Nintendo', ['3ds', '3dshacks', 'amiibo', 'nintendo', 'nintendoswitch', 'wiiu']),
    ('Sony', ['playstation', 'playstationplus', 'ps3', 'psvr', 'sony', 'vita']),
    ('PS4', ['ps4', 'ps4deals']),
    ('Individual Video Games/Series', ['animalcrossing', 'ark', 'arma', 'assassinscreed', 'bindingofisaac', 'bioshock', 'blackdesertonline', 'bloodborne', 'citiesskylines', 'civ', 'clashofclans', 'clashroyale', 'crusaderkings', 'cyberpunkgame', 'darkestdungeon', 'dayz', 'deadbydaylight', 'divinityoriginalsin', 'doom', 'dota2', 'dragonage', 'duellinks', 'dwarffortress', 'edh', 'elitedangerous', 'escapefromtarkov', 'eu4', 'eve', 'factorio', 'farcry', 'footballmanagergames', 'forhonor', 'forza', 'godofwar', 'grandorder', 'heroesofthestorm', 'hoi4', 'jrpg', 'kerbalspaceprogram', 'kingdomcome', 'kingdomhearts', 'masseffect', 'metalgearsolid', 'monsterhunter', 'monsterhunterworld', 'mountandblade', 'nomansskythegame', 'osugame', 'paladins', 'pathfinderrpg', 'pathofexile', 'paydaytheheist', 'persona5', 'playrust', 'reddeadredemption', 'rimworld', 'seaofthieves', 'smashbros', 'smite', 'spidermanps4', 'splatoon', 'starbound', 'starcitizen', 'starcraft', 'stardewvalley', 'stellaris', 'streetfighter', 'subnautica', 'summonerswar', 'terraria', 'thedivision', 'theexpanse', 'thelastofus', 'thesims', 'totalwar', 'undertale', 'warframe', 'warhammer', 'warhammer40k', 'warthunder', 'xcom']),
    ('Asian', ['asiancuties', 'asiangirlsbeingcute']),
    ('Borderlands', ['borderlands', 'borderlands2']),
    ('Dark Souls', ['darksouls', 'darksouls2', 'darksouls3']),
    ('Diablo', ['diablo', 'diablo3']),
    ('Elder Scrolls', ['elderscrolls', 'elderscrollsonline', 'teslore']),
    ('Skyrim', ['skyrim', 'skyrimmods']),
    ('Fallout', ['fallout', 'fo4', 'fo76']),
    ('Fire Emblem', ['fireemblem', 'fireemblemheroes']),
    ('Fortnite', ['fortnite', 'fortnitebattleroyale', 'fortnitebr', 'fortnitecompetitive', 'fortniteleaks']),
    ('Grand Theft Auto (GTA)', ['grandtheftautov', 'gtaonline', 'gtav']),
    ('Hearthstone', ['competitivehs', 'customhearthstone', 'hearthstone']),
    ('Minecraft', ['feedthebeast', 'minecraft']),
    ('Overwatch', ['competitiveoverwatch', 'overwatch', 'overwatch_memes', 'overwatchuniversity']),
    ('PUBG', ['pubattlegrounds', 'pubg', 'pubgmobile', 'pubgxboxone']),
    ('Rocket League', ['rocketleague', 'rocketleagueexchange']),
    ('Witcher', ['gwent', 'witcher']),
    ('First Person Shooters (fps)', ['rainbow6', 'shittyrainbow6', 'starwarsbattlefront', 'tf2', 'titanfall']),
    ('Battlefield', ['battlefield', 'battlefield_4', 'battlefield_one']),
    ('Genres', ['cyberpunk', 'zombies']),
    ('Fantasy', ['fantasy']),
    ('Sci-fi', ['asksciencefiction', 'empiredidnothingwrong', 'prequelmemes', 'sciencefiction', 'scifi', 'sequelmemes', 'startrek', 'starwars']),
    ('Internet/Apps', ['bannedfromclubpenguin', 'bestofworldstar', 'creepypms', 'discordapp', 'facepalm', 'google', 'internetisbeautiful', 'kenm', 'savedyouaclick', 'snaplenses', 'tronix', 'web_design', 'wikipedia']),
    ('4chan', ['4chan', 'classic4chan', 'greentext']),
    ('Facebook', ['facebookwins', 'facepalm', 'indianpeoplefacebook', 'insanepeoplefacebook', 'oldpeoplefacebook', 'terriblefacebookmemes']),
    ('Internet Dating', ['okcupid', 'tinder']),
    ('Internet Politics', ['kotakuinaction', 'shitcosmosays', 'wikileaks']),
    ('Live Streaming', ['livestreamfail', 'twitch']),
    ('Podcasts', ['podcasts', 'serialpodcast']),
    ('Tumblr', ['tumblr', 'tumblrinaction']),
    ('Twitter', ['blackpeopletwitter', 'latinopeopletwitter', 'scottishpeopletwitter', 'whitepeopletwitter', 'wholesomebpt']),
    ('YouTube', ['youtube', 'youtubehaiku']),
    ('Individual YouTubers/Companies', ['cgpgrey', 'cynicalbrit', 'defranco', 'gamegrumps', 'h3h3productions', 'idubbbz', 'jontron', 'loltyler1', 'pewdiepiesubmissions', 'pyrocynical', 'redlettermedia', 'sovietwomble', 'videogamedunkey', 'yogscast']),
    ('Roosterteeth', ['cowchop', 'funhaus', 'roosterteeth', 'rwby']),
    ('Movies', ['bollywoodrealism', 'cinematography', 'continuityporn', 'documentaries', 'fullmoviesonvimeo', 'fullmoviesonyoutube', 'ghibli', 'moviedetails', 'movies', 'moviesinthemaking', 'shittymoviedetails', 'truefilm']),
    ('Individual Movies/Series', ['harrypotter', 'lotr', 'lotrmemes', 'otmemes', 'starwars']),
    ('Comic movies', ['batman', 'dc_cinematic', 'marvelstudios', 'thanosdidnothingwrong']),
    ('Music', ['ableton', 'fakealbumcovers', 'futurebeats', 'guitarlessons', 'listentothis', 'mashups', 'music', 'musictheory', 'spotify', 'vinyl', 'wearethemusicmakers']),
    ('Artists', ['beatles', 'brockhampton', 'deathgrips', 'donaldglover', 'eminem', 'frankocean', 'gorillaz', 'kanye', 'kendricklamar', 'pinkfloyd', 'radiohead']),
    ('Music Genres', ['classicalmusic', 'gamemusic', 'indieheads', 'jazz', 'outrun', 'trap', 'vaporwave']),
    ('Electronic', ['dubstep', 'edm', 'edmproduction', 'electronicmusic']),
    ('Hip Hop', ['hiphopheads', 'hiphopimages']),
    ('Metal', ['metal', 'metalcore']),
    ('Pop', ['funkopop', 'kpop', 'popheads', 'spop']),
    ('Instruments', ['bass', 'drums', 'guitar', 'piano']),
    ('Sports', ['bicycling', 'cricket', 'discgolf', 'fishing', 'golf', 'rugbyunion', 'running', 'sailing', 'skiing', 'sports', 'sportsarefun', 'tennis']),
    ('American Football', ['cfb', 'fantasyfootball', 'nfl', 'nflstreams']),
    ('American Football Teams', ['eagles', 'greenbaypackers', 'minnesotavikings', 'patriots']),
    ('Baseball', ['baseball', 'fantasybaseball', 'mlb']),
    ('Basketball', ['collegebasketball', 'nba', 'nbastreams']),
    ('Teams', ['bostonceltics', 'lakers', 'torontoraptors', 'warriors']),
    ('Boards', ['longboarding', 'skateboarding', 'snowboarding']),
    ('Cars', ['formula1', 'nascar']),
    ('Fighting', ['boxing', 'mma', 'mmastreams', 'squaredcircle', 'theocho', 'ufc', 'wwe']),
    ('Hockey', ['hockey', 'leafs', 'nhl', 'nhlstreams']),
    ('Olympics', ['apocalympics2016', 'olympics']),
    ('Soccer', ['bundesliga', 'fantasypl', 'futbol', 'mls', 'soccer', 'worldcup']),
    ('Soccer Teams', ['chelseafc', 'gunners', 'liverpoolfc', 'reddevils']),
    ('TV', ['cordcutters', 'japanesegameshows', 'marvelstudios', 'offlinetv', 'shield', 'television', 'tvdetails']),
    ('Individual Shows', ['30rock', 'americanhorrorstory', 'arresteddevelopment', 'bettercallsaul', 'bigbrother', 'blackmirror', 'breakingbad', 'brooklynninenine', 'community', 'dundermifflin', 'filthyfrank', 'firefly', 'flashtv', 'gameofthrones', 'himym', 'houseofcards', 'howyoudoin', 'lifeisstrange', 'makingamurderer', 'mrrobot', 'orangeisthenewblack', 'pandr', 'riverdale', 'rupaulsdragrace', 'scrubs', 'sherlock', 'siliconvalleyhbo', 'startrek', 'strangerthings', 'supernatural', 'survivor', 'thegrandtour', 'thewalkingdead', 'topgear', 'trailerparkboys', 'truedetective', 'twinpeaks', 'westworld']),
    ('Animated', ['adventuretime', 'archerfx', 'bobsburgers', 'bojackhorseman', 'familyguy', 'futurama', 'gravityfalls', 'kingofthehill', 'mylittlepony', 'naruto', 'onepunchman', 'pokemon', 'rickandmorty', 'southpark', 'spongebob', 'stevenuniverse', 'thelastairbender', 'thesimpsons']),
    ('Dragon Ball Z', ['dbz', 'dbzdokkanbattle', 'dragonballfighterz']),
    ('Doctor Who', ['doctorwho', 'gallifrey']),
    ('It\'s Always Sunny in Philadelphia', ['iasip', 'the_dennis']),
    ('Seinfeld', ['redditwritesseinfeld', 'seinfeld', 'seinfeldgifs']),
    ('Netflix Related', ['bestofnetflix', 'netflix', 'netflixbestof']),
    ('Hobbies/Occupations - General', ['accounting', 'architecture', 'blacksmith', 'coolguides', 'cosplay', 'crochet', 'crossstitch', 'cubers', 'digitalnomad', 'diwhy', 'diy', 'dumpsterdiving', 'fastworkers', 'gunpla', 'ifyoulikeblank', 'knitting', 'modelmakers', 'preppers', 'protectandserve', 'redneckengineering', 'rtlsdr', 'sewing', 'somethingimade', 'urbanplanning', 'woodworking', 'worldbuilding']),
    ('Aquariums', ['aquariums', 'plantedtank']),
    ('Arts/Writing', ['alternativeart', 'art', 'artporn', 'coloringcorruptions', 'crafts', 'disneyvacation', 'drawing', 'glitch_art', 'illustration', 'restofthefuckingowl', 'sketchdaily']),
    ('Writing', ['calligraphy', 'fountainpens', 'handwriting', 'screenwriting', 'twosentencehorror', 'writing', 'writingprompts']),
    ('Automotive', ['autodetailing', 'autos', 'awesomecarmods', 'carporn', 'cars', 'cartalk', 'justrolledintotheshop', 'motorcycles', 'projectcar', 'roadcam', 'shitty_car_mods', 'tiresaretheenemy']),
    ('Car companies', ['bmw', 'jeep', 'subaru', 'teslamotors']),
    ('Design', ['assholedesign', 'atbge', 'crappydesign', 'design', 'designporn', 'dontdeadopeninside', 'graphic_design', 'interiordesign', 'keming', 'logodesign', 'tombstoning', 'web_design']),
    ('Fake it til you make it', ['actlikeyoubelong', 'irlsmurfing']),
    ('Guns/Combat - Combat', ['army', 'combatfootage', 'military', 'militarygfys', 'militaryporn', 'warshipporn']),
    ('Guns', ['airsoft', 'ar15', 'ccw', 'firearms', 'gundeals', 'gunporn', 'guns']),
    ('Job finding', ['cscareerquestions', 'forhire', 'jobs', 'workonline']),
    ('Music - Professional/Hobby', ['ableton', 'drums', 'edmproduction', 'fl_studio', 'guitar', 'piano', 'wearethemusicmakers']),
    ('Outdoors', ['backpacking', 'camping', 'campinggear', 'gardening', 'homestead', 'mtb', 'outdoors', 'survival', 'urbanexploration', 'wildernessbackpacking']),
    ('Hiking', ['campingandhiking', 'hiking', 'ultralight']),
    ('Photography/Film', ['analog', 'astrophotography', 'filmmakers', 'itookapicture', 'photocritique', 'photography']),
    ('Planes', ['aviation', 'flying']),
    ('Tech Related', ['compsci', 'engineering', 'graphic_design', 'itsaunixsystem', 'mechanicalkeyboards', 'multicopter', 'plex', 'programmerhumor', 'programminghorror', 'reverseengineering', 'sysadmin', 'webdev']),
    ('Coding', ['coding', 'cpp', 'dailyprogrammer', 'java', 'python']),
    ('PC Building', ['buildapc', 'buildapcforme', 'buildapcsales']),
    ('Tech Support', ['iiiiiiitttttttttttt', 'softwaregore', 'talesfromtechsupport', 'techsupport', 'techsupportgore']),
    ('Tools', ['knifeclub', 'knives', 'lockpicking', 'specializedtools', 'watches']),
    ('Travel', ['japantravel', 'solotravel', 'travel']),
    ('Lifestyle - General', ['edc', 'geek', 'lifehacks', 'lifeprotips', 'rainmeter', 'simpleliving', 'tinyhouses', 'unethicallifeprotips', 'vandwellers']),
    ('Gender', ['malelifestyle', 'malelivingspace', 'thegirlsurvivalguide']),
    ('Home', ['battlestations', 'homeautomation', 'homeimprovement', 'homelab', 'hometheater']),
    ('Communities', ['adhd', 'aliensamongus', 'bipolar', 'introvert', 'neverbrokeabone', 'polyamory', 'teachers', 'teenagers', 'totallynotrobots']),
    ('Body/Diet', ['beards', 'swoleacceptance', 'tall', 'vegan']),
    ('LGBT', ['actuallesbians', 'ainbow', 'askgaybros', 'bisexual', 'gay', 'gay_irl', 'gaybros', 'gaymers', 'lgbt']),
    ('Transgender', ['asktransgender', 'transgender']),
    ('Parenting', ['babybumps', 'daddit', 'parenting']),
    ('Alcohol', ['bourbon', 'cocktails', 'drunk', 'scotch', 'stopdrinking', 'whiskey', 'wine']),
    ('Beer', ['beer', 'beerporn', 'homebrewing', 'showerbeer']),
    ('Marijuana', ['cannabis', 'eldertrees', 'leaves', 'marijuana', 'microgrowery', 'see', 'trees', 'weed', 'weedstocks']),
    ('Other drugs', ['dmt', 'drugs', 'electronic_cigarette', 'lsd', 'nootropics', 'shrooms', 'stonerengineering', 'stopsmoking', 'vaping', 'vaporents']),
    ('Exercise/Health', ['getmotivated', 'health', 'medicine', 'zenhabits']),
    ('Mental', ['luciddreaming', 'meditation', 'mentalhealth', 'psychonaut']),
    ('Physical', ['fitness', 'xxfitness']),
    ('Diet', ['fasting', 'fitmeals', 'healthyfood', 'intermittentfasting', 'leangains', 'nutrition', 'paleo', 'vegetarian']),
    ('Keto', ['keto', 'ketogains', 'ketorecipes']),
    ('Exercise', ['backpacking', 'bicycling', 'bjj', 'climbing', 'crossfit', 'skateboarding', 'skiing', 'yoga']),
    ('Lifting/Weights', ['bodybuilding', 'powerlifting', 'weightroom']),
    ('Running', ['c25k', 'running']),
    ('Weight/Body Shape Control', ['bodyweightfitness', 'flexibility', 'gainit', 'loseit', 'swoleacceptance']),
    ('Progress Pictures', ['brogress', 'progresspics']),
    ('Fashion/Beauty - Body Image', ['asianbeauty', 'beards', 'makeupaddiction', 'piercing', 'redditlaqueristas', 'skincareaddiction', 'wicked_edge']),
    ('Hair', ['curlyhair', 'fancyfollicles', 'malehairadvice']),
    ('Tattoos', ['badtattoos', 'tattoo', 'tattoos']),
    ('Fashion', ['fashion', 'fashionreps', 'femalefashionadvice', 'frugalmalefashion', 'malefashion', 'malefashionadvice', 'streetwear', 'supremeclothing', 'thriftstorehauls']),
    ('Shoes', ['goodyearwelt', 'repsneakers', 'sneakers']),
    ('Food', ['eatsandwiches', 'food', 'foodhacks', 'foodporn', 'forbiddensnacks', 'mealtimevideos', 'nutrition', 'seriouseats', 'shittyfoodporn', 'wewantplates']),
    ('Cooking', ['askculinary', 'baking', 'breadit', 'castiron', 'cooking', 'cookingforbeginners', 'instantpot', 'mealprepsunday', 'slowcooking', 'smoking']),
    ('Diets', ['1200isplenty', 'budgetfood', 'cheap_meals', 'eatcheapandhealthy', 'fasting', 'fitmeals', 'healthyfood', 'intermittentfasting', 'ketorecipes', 'vegan', 'veganrecipes']),
    ('Drinks (non-alcoholic)', ['coffee', 'tea']),
    ('Recipes', ['gifrecipes', 'recipes', 'veganrecipes']),
    ('Specific food', ['bbq', 'grilledcheese', 'pizza', 'ramen', 'sushi']),
    ('Money', ['antimlm', 'apphookup', 'beermoney', 'churning', 'economy', 'entrepreneur', 'finance', 'financialindependence', 'flipping', 'iota', 'personalfinance', 'realestate', 'ripple', 'startups', 'stellar']),
    ('Betting/Investing/Stocks', ['investing', 'millionairemakers', 'wallstreetbets', 'weedstocks']),
    ('Budget', ['budgetfood', 'cheap_meals', 'eatcheapandhealthy', 'frugal', 'frugal_jerk', 'frugalmalefashion', 'povertyfinance']),
    ('Consumerism', ['anticonsumption', 'buyitforlife', 'crappyoffbrands', 'sbubby', 'shouldibuythisgame', 'shutupandtakemymoney', 'wellworn']),
    ('CryptoCurrency', ['bitcoin', 'btc', 'cardano', 'cryptocurrency', 'dogecoin', 'ethereum', 'ethtrade', 'garlicoin', 'litecoin', 'vechain']),
    ('Religion/Beliefs', ['buddhism', 'occult', 'psychonaut', 'stoicism']),
    ('Atheism', ['atheism', 'trueatheism']),
    ('Christianity', ['catholicism', 'christianity', 'dankchristianmemes', 'exmormon']),
    ('Philosophy', ['askphilosophy', 'philosophy']),
    ('Relationships/Sex', ['socialengineering', 'socialskills', 'weddingplanning']),
    ('Family', ['childfree', 'daddit', 'justnofamily', 'justnomil', 'parenting', 'raisedbynarcissists']),
    ('Relationships', ['dating_advice', 'relationship_advice', 'relationships']),
    ('Online Relationships', ['dirtyr4r', 'longdistance', 'okcupid', 'r4r', 'tinder']),
    ('Sex', ['deadbedrooms', 'nofap', 'polyamory', 'seduction', 'sex']),
    ('Self-Improvement', ['decidingtobebetter', 'getdisciplined', 'getmotivated', 'getstudying', 'happy', 'happycrowds', 'humansbeingbros', 'iwantout', 'mademesmile', 'productivity', 'quotesporn', 'selfimprovement', 'sportsarefun']),
    ('Technology', ['aboringdystopia', 'buildapc', 'cableporn', 'compsci', 'crackwatch', 'design', 'engineering', 'engineeringporn', 'futurology', 'gamedev', 'hacking', 'imaginarytechnology', 'infographics', 'internetisbeautiful', 'jailbreak', 'netsec', 'networking', 'onions', 'opensource', 'pcmasterrace', 'php', 'piracy', 'privacy', 'simulated', 'talesfromtechsupport', 'tech', 'torrents', 'unixporn', 'virtualreality']),
    ('3D Printing', ['3dprinting', 'functionalprint']),
    ('Business Tech', ['amd', 'firefox', 'nasa', 'nintendo', 'nvidia', 'photoshop', 'spacex']),
    ('Android products', ['android', 'androidapps', 'androiddev', 'androidgaming', 'androidthemes', 'oneplus']),
    ('Apple Products', ['apple', 'applewatch', 'ipad', 'iphone', 'mac']),
    ('Gadgets', ['amazonecho', 'arduino', 'blender', 'electronics', 'gadgets', 'gopro', 'raspberry_pi', 'retropie', 'trackers']),
    ('Hardware', ['hardware', 'hardwareswap']),
    ('Kodi', ['addons4kodi', 'kodi']),
    ('Google Products', ['chromecast', 'google', 'googlehome', 'googlepixel']),
    ('Linux', ['archlinux', 'linux', 'linux4noobs', 'linux_gaming', 'linuxmasterrace']),
    ('Microsoft Products', ['excel', 'microsoft', 'surface', 'windows', 'windows10']),
    ('Data', ['datahoarder', 'dataisbeautiful']),
    ('Digital Currency', ['bitcoin', 'bitcoinmarkets', 'btc', 'cryptocurrency', 'cryptomarkets', 'dogecoin', 'ethereum', 'ethtrader', 'litecoin', 'monero', 'neo']),
    ('Programming', ['excel', 'java', 'javascript', 'learnprogramming', 'learnpython', 'programming', 'python', 'unity3d']),
    ('Sound', ['audioengineering', 'audiophile', 'headphones']),
    ('Humor - General Humor', ['accidentalcomedy', 'childrenfallingover', 'comedycemetery', 'comedyheaven', 'comedyhomicide', 'comedynecromancy', 'contagiouslaughter', 'dadreflexes', 'funny', 'funnyandsad', 'humor', 'kenm', 'kidsarefuckingstupid', 'notkenm', 'politicalhumor', 'prematurecelebration', 'programmerhumor', 'standupcomedy']),
    ('Jokes', ['3amjokes', 'antijokes', 'dadjokes', 'darkjokes', 'jokes', 'meanjokes', 'punny', 'puns', 'standupshots', 'wordavalanches']),
    ('Memes/Rage comics', ['copypasta', 'demotivational', 'emojipasta', 'lolcats', 'supershibe']),
    ('Memes and Rage Comics', ['starterpacks', 'trollxchromosomes', 'trollychromosome']),
    ('Memes', ['absoluteunits', 'adviceanimals', 'animemes', 'bidenbro', 'bikinibottomtwitter', 'bonehurtingjuice', 'bossfight', 'dank_meme', 'dankchristianmemes', 'dankmemes', 'deepfriedmemes', 'delightfullychubby', 'equelmemes', 'garlicbreadmemes', 'gocommitdie', 'historymemes', 'ilikthebred', 'kappa', 'lotrmemes', 'madlads', 'meme', 'memeeconomy', 'memes', 'memes_of_the_dank', 'namflashbacks', 'otmemes', 'overwatch_memes', 'prequelmemes', 'rarepuppers', 'see', 'sequelmemes', 'smoobypost', 'suddenlygay', 'surrealmemes', 'terriblefacebookmemes', 'trebuchetmemes', 'trippinthroughtime', 'wholesomegreentext', 'wholesomememes']),
    ('____irl', ['2meirl4meirl', 'absolutelynotme_irl', 'absolutelynotmeirl', 'anime_irl', 'me_irl', 'meirl', 'meow_irl', 'toomeirlformeirl', 'woof_irl']),
    ('Rage Comics', ['fffffffuuuuuuuuuuuu', 'iiiiiiitttttttttttt']),
    ('Animals', ['animalporn', 'animalsbeingbros', 'animalsbeingderps', 'animalsbeingjerks', 'animalsthatlovemagic', 'animaltextgifs', 'beforenafteradoption', 'bigboye', 'brushybrushy', 'curledfeetsies', 'floof', 'hitmanimals', 'hybridanimals', 'likeus', 'mlem', 'properanimalnames', 'shittyanimalfacts', 'sneks', 'spiderbro', 'stoppedworking', 'tsunderesharks', 'whatsthisbug', 'zoomies']),
    ('Birds', ['birbs', 'birdsbeingdicks', 'birdswitharms', 'emuwarflashbacks', 'partyparrot', 'superbowl']),
    ('Mammals', ['babyelephantgifs', 'foxes', 'goatparkour', 'happycowgifs', 'rabbits', 'sloths', 'trashpandas']),
    ('Cats', ['babybigcatgifs', 'bigcatgifs', 'blackcats', 'catgifs', 'catloaf', 'catpictures', 'catpranks', 'cats', 'catsareassholes', 'catsareliquid', 'catsisuottatfo', 'catslaps', 'catsstandingup', 'cattaps', 'holdmycatnip', 'jellybeantoes', 'meow_irl', 'startledcats', 'stuffoncats', 'supermodelcats', 'teefies', 'thecatdimension', 'thisismylifemeow', 'tuckedinkitties']),
    ('Dogs', ['barkour', 'blop', 'dogberg', 'dogpictures', 'dogs', 'dogswithjobs', 'dogtraining', 'masterreturns', 'petthedamndog', 'puppies', 'puppysmiles', 'whatswrongwithyourdog', 'woof_irl']),
    ('Breeds', ['babycorgis', 'corgi', 'goldenretrievers', 'incorgnito', 'pitbulls']),
    ('Conspiracy', ['conspiracy', 'conspiratard', 'empiredidnothingwrong', 'karmaconspiracy', 'scp', 'skeptic', 'ufos']),
    ('Cringe', ['4panelcringe', 'accidentalracism', 'amibeingdetained', 'blunderyears', 'corporatefacepalm', 'cringe', 'cringepics', 'engrish', 'facepalm', 'fatlogic', 'fellowkids', 'instant_regret', 'instantbarbarians', 'lewronggeneration', 'masterhacker', 'publicfreakout', 'sadcringe', 'technicallythetruth', 'watchpeopledieinside', 'wokekids']),
    ('Called out', ['atetheonion', 'badfaketexts', 'beholdthemasterrace', 'boneappletea', 'delusionalartists', 'delusionalcraigslist', 'dontfundme', 'dontyouknowwhoiam', 'facepalm', 'facingtheirparenting', 'goodfaketexts', 'iamatotalpieceofshit', 'ihadastroke', 'ihavesex', 'lostredditors', 'murderedbywords', 'nobodyasked', 'nothingeverhappens', 'oopsdidntmeanto', 'phonesarebad', 'quityourbullshit', 'suicidebywords', 'suspiciousquotes', 'thathappened', 'topmindsofreddit', 'untrustworthypoptarts', 'vaxxhappened', 'woooosh', 'wowthanksimcured']),
    ('"Neckbeard"', ['choosingbeggars', 'creepyasterisks', 'gatekeeping', 'humblebrag', 'iamverybadass', 'iamverysmart', 'inceltears', 'justneckbeardthings', 'mallninjashit', 'neckbeardnests', 'neckbeardrpg', 'nicegirls', 'niceguys', 'nothowdrugswork', 'whiteknighting']),
    ('Cute', ['animalsbeingbros', 'animalsbeingjerks', 'aww', 'awwducational', 'awww', 'babycorgis', 'blep', 'cats', 'corgi', 'dogs', 'eyebeach', 'thisismylifenow', 'tippytaps']),
    ('Disgusting/Angering/Scary/Weird (Note: Potentially NSFL)', ['awwwtf', 'deepintoyoutube', 'fifthworldproblems', 'maybemaybemaybe', 'oddlyterrifying', 'streetfights', 'thatlookedexpensive', 'wellthatsucks', 'whatthefuckgetitoffme', 'wtf', 'wtfgaragesale', 'wtfstockphotos', 'yesyesyesno', 'yesyesyesyesno']),
    ('Angering', ['bad_cop_no_donut', 'crappydesign', 'fuckthesepeople', 'gifsthatendtoosoon', 'mildlyinfuriating', 'peoplebeingjerks', 'rage']),
    ('Edgy', ['imgoingtohellforthis']),
    ('Judgy', ['13or30', 'awfuleverything', 'awfuleyebrows', 'ghettoglamourshots', 'hittablefaces', 'peopleofwalmart', 'punchablefaces', 'trashy']),
    ('Scary (potentially NSFL)', ['glitch_in_the_matrix', 'horror', 'lastimages', 'morbidreality', 'nononono', 'nosleep', 'paranormal', 'peoplefuckingdying', 'serialkillers', 'shortscarystories', 'whatcouldgowrong', 'whyweretheyfilming', 'winstupidprizes']),
    ('Creepy', ['creepy', 'creepypasta', 'megalophobia']),
    ('Imaginary', ['imaginarycharacters', 'imaginarylandscapes', 'imaginaryleviathans', 'imaginarymaps', 'imaginarymindscapes', 'imaginarymonsters', 'sympatheticmonsters']),
    ('Water is scary', ['submechanophobia', 'thalassophobia', 'thedepthsbelow']),
    ('Free Stuff', ['coupons', 'dealsreddit', 'efreebies', 'freebies', 'freeebooks', 'freegamefindings', 'freegamesonsteam', 'fullmoviesonvimeo', 'fullmoviesonyoutube', 'googleplaydeals', 'opendirectories', 'random_acts_of_pizza', 'randomactsofgaming']),
    ('For Men', ['askmen', 'bigdickproblems', 'everymanshouldknow', 'frugalmalefashion', 'malefashion', 'malefashionadvice', 'malehairadvice', 'malelifestyle', 'malelivingspace', 'mensrights', 'mgtow', 'trollychromosome']),
    ('For Women', ['abrathatfits', 'askwomen', 'badwomensanatomy', 'femalefashionadvice', 'ladyboners', 'thegirlsurvivalguide', 'trollxchromosomes', 'twoxchromosomes', 'xxfitness']),
    ('Geography', ['mapporn', 'polandball', 'vexillology']),
    ('Africa', ['southafrica']),
    ('Europe', ['austria', 'belgium', 'denmark', 'europe', 'ireland', 'italy', 'norge', 'polska', 'romania', 'scotland', 'suomi', 'thenetherlands']),
    ('France', ['france', 'french']),
    ('Germany', ['de', 'german', 'germany']),
    ('Russia', ['anormaldayinrussia', 'youseecomrade']),
    ('Sweden', ['allsvenskan', 'intresseklubben', 'spop', 'svenskpolitik', 'swarje', 'sweden', 'swedishproblems']),
    ('United Kingdom', ['britishproblems', 'casualuk', 'london', 'ukpolitics', 'unitedkingdom']),
    ('Canada', ['calgary', 'canada', 'canadapolitics', 'toronto', 'vancouver']),
    ('Mexico', ['mexico']),
    ('USA: United States of America', ['atlanta', 'boston', 'chicago', 'michigan', 'minnesota', 'murica', 'newjersey', 'nyc', 'philadelphia', 'portland', 'washingtondc']),
    ('California', ['bayarea', 'california', 'disneyland', 'losangeles', 'sandiego', 'sanfrancisco']),
    ('Colorado', ['colorado', 'denver']),
    ('Florida', ['floridaman', 'waltdisneyworld']),
    ('Texas', ['austin', 'dallas', 'houston', 'texas']),
    ('Washington', ['seattle', 'seattlewa']),
    ('Oceania', ['australia', 'melbourne', 'newzealand', 'sydney']),
    ('Asia', ['china', 'hongkong', 'india', 'philippines', 'singapore']),
    ('Japan', ['japan', 'japanpics', 'japantravel']),
    ('Korea', ['korea', 'kpop', 'pyongyang']),
    ('South America', ['argentina', 'brasil']),
    ('Meta', ['againsthatesubreddits', 'beetlejuicing', 'enhancement', 'evenwithcontext', 'modnews', 'museumofreddit', 'nocontext', 'outoftheloop', 'redditinreddit', 'secretsanta', 'theoryofreddit', 'threadkillers', 'tldr']),
    ('Administrative', ['announcements', 'beta', 'blog']),
    ('Apps', ['alienblue', 'apolloapp', 'baconit', 'baconreader', 'redditmobile', 'redditsync', 'relayforreddit']),
    ('Circlejerks', ['circlejerk', 'diwhy', 'frugal_jerk']),
    ('Drama', ['drama', 'hobbydrama', 'subredditdrama']),
    ('Negative', ['jesuschristreddit', 'karmaconspiracy', 'karmacourt', 'shitamericanssay', 'shitredditsays', 'titlegore', 'undelete']),
    ('Positive', ['bestof', 'bestoflegaladvice', 'bestofreports', 'depthhub']),
    ('Subreddits', ['findareddit', 'newreddits', 'ofcoursethatsathing', 'subredditoftheday', 'wowthissubexists']),
    ('Subreddit Simulator', ['subredditsimmeta', 'subredditsimulator']),
    ('General', ['awesome', 'truereddit']),
    ('Looking for something', ['tipofmytongue']),
    ('Mind blowing', ['asmr', 'frisson', 'glitchinthematrix', 'vaporwaveaesthetics', 'woahdude']),
    ('Nature', ['earthporn', 'hardcoreaww', 'heavyseas', 'hitmanimals', 'natureisfuckinglit']),
    ('Plants/Fungi', ['bonsai', 'marijuanaenthusiasts', 'mycology', 'succulents', 'treessuckingonthings']),
    ('Violent Nature', ['natureisbrutal', 'natureismetal', 'naturewasmetal']),
    ('Weather', ['tropicalweather', 'weathergifs']),
    ('News/Politics - News', ['energy', 'floridaman', 'gamernews', 'news', 'nottheonion', 'offbeat', 'syriancivilwar', 'truecrime', 'upliftingnews', 'worldnews']),
    ('Fake News', ['atetheonion', 'theonion']),
    ('Politics', ['anarchism', 'communism', 'completeanarchy', 'conservative', 'geopolitics', 'libertarian', 'neutralpolitics', 'politicaldiscussion', 'politicalhumor', 'politics', 'socialism', 'ukpolitics', 'worldpolitics']),
    ('Capitalism', ['anarcho_capitalism', 'latestagecapitalism']),
    ('Gender Politics', ['feminism', 'mensrights']),
    ('Left', ['bidenbro', 'bluemidterm2018', 'democrats', 'esist', 'fuckthealtright', 'keep_track', 'liberal', 'political_revolution', 'sandersforpresident', 'thanksobama', 'the_mueller']),
    ('Anti-Trump', ['enoughtrumpspam', 'impeach_trump', 'marchagainsttrump', 'tinytrumps', 'trumpcriticizestrump', 'trumpgret']),
    ('Nostalgia/Time', ['forwardsfromgrandma', 'nostalgia', 'oldphotosinreallife', 'oldschoolcool', 'thewaywewere', 'vinyl']),
    ('Parodies', ['accidentalrenaissance', 'bollywoodrealism', 'coaxedintoasnafu', 'fakehistoryporn', 'firstworldanarchists', 'hailcorporate', 'im14andthisisdeep', 'irleastereggs', 'maliciouscompliance', 'montageparodies', 'osha', 'outside', 'unexpectedthuglife', 'wheredidthesodago', 'youdontsurf']),
    ('SFWPorn Network', ['abandonedporn', 'adporn', 'adrenalineporn', 'animalporn', 'architectureporn', 'artefactporn', 'artporn', 'cabinporn', 'carporn', 'cityporn', 'designporn', 'destructionporn', 'earthporn', 'exposureporn', 'foodporn', 'futureporn', 'gunporn', 'historyporn', 'houseporn', 'humanporn', 'illusionporn', 'infrastructureporn', 'justiceporn', 'machineporn', 'macroporn', 'mapporn', 'microporn', 'militaryporn', 'mineralporn', 'movieposterporn', 'penmanshipporn', 'powerwashingporn', 'productporn', 'quotesporn', 'roomporn', 'shockwaveporn', 'skyporn', 'spaceporn', 'thingscutinhalfporn', 'villageporn', 'waterporn']),
    ('Shitty', ['crappydesign', 'shitpost', 'shitty_car_mods', 'shittyadvice', 'shittyanimalfacts', 'shittyaskscience', 'shittyfoodporn', 'shittykickstarters', 'shittylifeprotips', 'shittymoviedetails', 'shittyreactiongifs', 'shittyrobots']),
    ('Unexpected', ['blackmagicfuckery', 'misleadingthumbnails', 'slygifs', 'unexpected', 'unexpectedhogwarts', 'unexpectedjihad', 'unexpectedmulaney', 'unexpectedthuglife']),
    ('Visually Appealing', ['abandonedporn', 'accidentalwesanderson', 'amateurroomporn', 'breathinginformation', 'cinemagraphs', 'cityporn', 'cozyplaces', 'designporn', 'desirepath', 'eyebleach', 'handwriting', 'humansbeingbros', 'imaginarylandscapes', 'minimalism', 'mostbeautiful', 'nevertellmetheodds', 'nonononoyes', 'oddlysatisfying', 'penmanshipporn', 'perfectfit', 'perfectloops', 'powerwashingporn', 'raining', 'roomporn', 'slygifs', 'thatpeelingfeeling', 'tiltshift', 'typography', 'unstirredpaint']),
    ('Hold My ____', ['holdmybeaker', 'holdmybeer', 'holdmycatnip', 'holdmycosmo', 'holdmyfeedingtube', 'holdmyfries', 'holdmyjuicebox', 'holdmyredbull']),
    ('Uncategorized', ['2healthbars', 'bitchimabus', 'bizarrebuildings', 'boop', 'catastrophicfailure', 'collapse', 'confusing_perspective', 'dashcamgifs', 'dontputyourdickinthat', 'drunkorakid', 'evilbuildings', 'expanddong', 'fifthworldpics', 'fiftyfifty', 'firstworldproblems', 'fullscorpion', 'greendawn', 'hadtohurt', 'halloween', 'happycryingdads', 'hmmm', 'hmmmgifs', 'idiotsfightingthings', 'idiotsincars', 'inclusiveor', 'instantkarma', 'instantregret', 'justfuckmyshitup', 'justiceserved', 'kurzgesagt', 'lostgeneration', 'mandelaeffect', 'mildlypenis', 'mildlyvandalised', 'mypeopleneedme', 'nextfuckinglevel', 'notinteresting', 'notmyjob', 'okbuddyretard', 'onejob', 'ooer', 'pussypassdenied', 'redditdayof', 'slavs_squatting', 'sweatypalms', 'tendies', 'the_pack', 'therewasanattempt', 'thingsforants', 'tworedditorsonecup', 'unbgbbiivchidctiicbg', 'unpopularopinion', 'urbanhell', 'wackytictacs', 'watchpeoplesurvive', 'whatcouldgoright', 'whatintarnation', 'whatsinthisthing', 'youseeingthisshit']),
]

# make sure there are no duplicate category names
assert len(SUBREDDIT_INFO) == len(dict(SUBREDDIT_INFO))

SUBREDDITS = {s for _, subreddits in SUBREDDIT_INFO for s in subreddits}
