#!/usr/bin/env python3
import os

import praw


SUBREDDIT_NAMES = [
    'aviation',
    'spacex',
    'python',
    'technology',
    'piano',
]

REDDIT_CLIENT_ID = os.environ.get('REDDIT_CLIENT_ID')
REDDIT_CLIENT_SECRET = os.environ.get('REDDIT_CLIENT_SECRET')
REDDIT_USERNAME = os.environ.get('REDDIT_USERNAME')
REDDIT_PASSWORD = os.environ.get('REDDIT_PASSWORD')


def summer():
    reddit = praw.Reddit(client_id=REDDIT_CLIENT_ID,
                         client_secret=REDDIT_CLIENT_SECRET,
                         username=REDDIT_USERNAME,
                         password=REDDIT_PASSWORD,
                         user_agent='summer by /u/deneb150')
    for name in SUBREDDIT_NAMES:
        print(f'Top posts from last 24 hours in subreddit: {name}')
        for result in reddit.subreddit(name).top('day', limit=10):
            print(f' - {result.title}')


if __name__ == '__main__':
    summer()
