#!/usr/bin/env python3
from praw_client import get_reddit

from app import db, Subreddit


def summer():
    reddit = get_reddit()
    for name in :
        print(f'Top posts from last 24 hours in subreddit: {name}')
        for result in reddit.subreddit(name).top('day', limit=10):
            print(f' - {result.title}')


if __name__ == '__main__':
    summer()
