apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orangered
  labels:
    app: orangered

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: orangered
    spec:
      containers:
        - name: orangered
          image: orangered
          imagePullPolicy: Never
          env:
            - name: SQLALCHEMY_DATABASE_URI
              value: postgres://orangered_user:orangered@postgres:5432/orangered
