apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orangered
  labels:
    app: orangered

# The orangered worker replica set ensures that at least 2 instances of the
# orangered worker pod are running on the cluster.
# For more info about Pods see:
#   https://cloud.google.com/kubernetes-engine/docs/pods/
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: orangered
        tier: orangered
    spec:
      containers:
        - name: orangered
          image: gcr.io/orangered/orangered
          # This setting makes nodes pull the docker image every time before
          # starting the pod. This is useful when debugging, but should be turned
          # off in production.
          imagePullPolicy: Always
          # The PROCESSES environment variable is used by Honcho in the
          # Dockerfile's CMD to control which processes are started. In this
          # case, only the worker process is needed.
          env:
            - name: PROCESSES
              value: orangered
