apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orangered
  labels:
    app: orangered

spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: orangered
    spec:
      containers:
        - name: orangered
          image: gcr.io/orangered/orangered
          env:
            - name: SQLALCHEMY_DATABASE_URI
              value: postgresql://127.0.0.1/orangered

